/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/assets/glasses/rayban_test.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Hooks_geo.geometry}
        material={materials.standardSurface4}
      />
      {/* Bridge */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Frame_geo.geometry}
        material={materials.standardSurface4}
      />
      {/* Branches */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Splints_geo.geometry}
        material={materials.standardSurface4}
      />
      {/* ? */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chrome_geo.geometry}
        material={materials.standardSurface4}
      />
      {/* ? */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Badge_RayBan_geo1.geometry}
        material={materials.standardSurface4}
      />
      {/* ? */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Badge_RayBan_geo.geometry}
        material={materials.standardSurface4}
      />
      {/* Glasses */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Glass_geo.geometry}
        material={materials.standardSurface4}
      />
    </group>
  );
}

useGLTF.preload("/assets/glasses/rayban_test.glb");
